name: Deploy to Lightsail

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add Lightsail to SSH known hosts
      run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "35.74.156.53 $(ssh-keyscan 35.74.156.53 2>/dev/null)" >> ~/.ssh/known_hosts

    - name: Deploy to Lightsail
      env:
          PRIVATE_KEY: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -i private_key.pem -r * bitnami@35.74.156.53:/path/to/your/project
        rm -f private_key.pem


